export const SAVE_USER = 'SAVE_USER'
export const ADD_EXPENSE = 'ADD_EXPENSE'
export const EDIT_EXPENSE = 'EDIT_EXPENSE'
export const DELETE_EXPENSE = 'DELETE_EXPENSE'
export const ADD_GOAL = 'ADD_GOAL'
export const DELETE_GOAL = 'DELETE_GOAL'
export const UPDATE_GOAL = 'UPDATE_GOAL'

export const TOTAL_INCOME = 'TOTAL_INCOME'
export const ACCOUNTS = 'ACCOUNTS'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const CHECK_PREMIUM = 'CHECK_PREMIUM'
export const INVESTMENT = 'INVESTMENT'
export const DELETE_INVESTMENT = 'DELETE_INVESTMENT'

export const GOAL_DEPOSIT = 'GOAL_DEPOSIT'

export const SAVE_CARD = 'SAVE_CARD'
export const DELETE_CREDIT = 'DELETE_CREDIT'

export const UPDATE_CREDIT = 'UPDATE_CREDIT'
export const UPDATE_DEBIT = 'UPDATE_DEBIT'
export const DARK_MODE = 'DARK_MODE'